# Generated by Django 5.2.8 on 2025-11-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_code', models.CharField(blank=True, db_index=True, max_length=10, unique=True)),
                ('image', models.ImageField(upload_to='shinies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
